networks:
  - - { layer_type: convolution,
        activation: 'tanh',
        bias: False,
        heads: [1],
        labels: [
          { label_type: [wl_labeled], depth: [3] },
        ],
        properties: [
          { name: distances, values: [ 0,1,2,3,4,5,6] },
        ]
  }
    - { layer_type: aggregation,
        activation: 'tanh',
        bias: True,
        heads: [1],
        labels: [
          { label_type: primary },
        ]
    }
    - { layer_type: reshape }



input_features: {name: constant, value: 1.0}