networks:
  - - { layer_type: convolution,
        activation: 'tanh',
        bias: False,
        heads: [1],
        labels: [
          { label_type: [wl_labeled], depth: [3,2,1,0] },
          { label_type: [simple_cycles, primary], max_cycle_length: [6, 10, 20] },
          { label_type: [induced_cycles, primary], max_cycle_length: [10, 20] },
          { label_type: primary }
        ],
        properties: [
          { name: distances, values: [ 0,1,2,3,4,5,6 ] },
        ]
  }
    - { layer_type: aggregation,
        activation: 'tanh',
        bias: True,
        heads: [1],
        labels: [
          { label_type: [wl_labeled], depth: [3,2,1,0] },
          { label_type: [simple_cycles, primary], max_cycle_length: [6, 10, 20] },
          { label_type: [induced_cycles, primary], max_cycle_length: [10, 20] },
          { label_type: primary },
        ]
    }
    - { layer_type: reshape }