networks:
  - - { layer_type: convolution,
        activation: 'tanh',
        bias: False,
        heads: [1],
        labels: [
          { label_type: simple_cycles, max_cycle_length: [ 10 ] }
        ],
        properties: [
          { name: distances, values: [ 0, 1 ] }
        ]
  }
    - { layer_type: aggregation,
        activation: 'tanh',
        bias: True,
        heads: [1],
        labels: [
          { label_type: simple_cycles, max_cycle_length: [ 10 ] }
        ]
    }
    - { layer_type: reshape }
