networks:
  # mixed models
  - - { layer_type: convolution,
        activation: 'tanh',
        bias: False,
        heads: [1],
        labels: [
          { label_type: primary}
        ],
        properties: [
          { name: distances, values: [ 0, 50 ] }
        ]
      }
    - { layer_type: aggregation,
        activation: 'tanh',
        bias: True,
        heads: [1],
        labels: [
          { label_type: primary }
        ]
    }
    - { layer_type: reshape }