networks:
  - - { layer_type: convolution ,
      bias: False,
        activation: 'LeakyReLU',
      heads: [
        {
          bias: False,
          labels: {
            head: { label_type: simple_cycles, min_cycle_length: 3 , max_cycle_length: 3 },
            tail: { label_type: simple_cycles, min_cycle_length: 3 , max_cycle_length: 3 },
            bias: { label_type: simple_cycles, min_cycle_length: 3 , max_cycle_length: 3 },
          },
          properties:
            { name: distances, values: [ 0 ] },
        },
        {
          bias: False,
          labels: {
            head: { label_type: simple_cycles, min_cycle_length: 4 , max_cycle_length: 4 },
            tail: { label_type: simple_cycles, min_cycle_length: 4 , max_cycle_length: 4 },
            bias: { label_type: simple_cycles, min_cycle_length: 4 , max_cycle_length: 4 },
          },
          properties:
            { name: distances, values: [ 0 ] },
        },
        {
          bias: False,
          labels: {
            head: { label_type: simple_cycles, min_cycle_length: 5 , max_cycle_length: 5 },
            tail: { label_type: simple_cycles, min_cycle_length: 5 , max_cycle_length: 5 },
            bias: { label_type: simple_cycles, min_cycle_length: 5 , max_cycle_length: 5 },
          },
          properties:
            { name: distances, values: [ 0 ] },
        },
        {
          bias: False,
          labels: {
            head: { label_type: simple_cycles, min_cycle_length: 6 , max_cycle_length: 6 },
            tail: { label_type: simple_cycles, min_cycle_length: 6 , max_cycle_length: 6 },
            bias: { label_type: simple_cycles, min_cycle_length: 6 , max_cycle_length: 6 },
          },
          properties:
            { name: distances, values: [ 0 ] },
        },
        {
          bias: False,
          labels: {
            head: { label_type: wl, depth: 0 },
            tail: { label_type: wl, depth: 0 },
            bias: { label_type: wl, depth: 0 },
          },
          properties:
            { name: distances, values: [ 0,1,2,3,4,5,6,7,8,9,10 ] },
        }
      ],
  }
    - { layer_type: linear,
        mode: 'aggr_heads',
        output_features: 10,
        bias: True,
        activation: 'LeakyReLU'
    }
    - { layer_type: layer_norm }
    - { layer_type: aggregation,
        activation: 'LeakyReLU',
        bias: True,
        out_dim: 10,
        heads: [
          {
            bias: True,
            labels: { label_type: simple_cycles, min_cycle_length: 3 , max_cycle_length: 3 },
          },
          {
            bias: True,
            labels: { label_type: simple_cycles, min_cycle_length: 4, max_cycle_length: 4 },
          },
          {
            bias: True,
            labels: { label_type: simple_cycles, min_cycle_length: 5, max_cycle_length: 5 },
          },
          {
            bias: True,
            labels: { label_type: simple_cycles, min_cycle_length: 6, max_cycle_length: 6 },
          },
          {
            bias: True,
            labels: { label_type: wl, depth: 0 },
          }
        ],
    }
    - { layer_type: reshape}
    - { layer_type: linear,
        mode: 'aggr_features',
        output_features: 6,
        bias: True,
        activation: 'LeakyReLU'
    }
    - { layer_type: reshape}