networks:
  - - { layer_type: linear,
        mode: 'aggr_features',
        output_features: 10,
        bias: True,
        activation: 'LeakyReLU',
  }
    - { layer_type: layer_norm }
    - { layer_type: convolution ,
        bias: True,
        activation: 'None',
        heads: [
          {
            bias: True,
            labels: {
              head: { label_type: [ induced_cycles, wl_labeled ], min_cycle_length: 6 , max_cycle_length: 6, depth: 0 },
              tail: { label_type: [ induced_cycles, wl_labeled ], min_cycle_length: 6 , max_cycle_length: 6, depth: 0 },
              bias: { label_type: wl_labeled_edges, depth: 1 },
            },
            properties:
              { name: distances, values: [1,2,3,4,5,6 ] },
          },
          {
            bias: True,
            labels: {
              head: { label_type: [ induced_cycles, wl_labeled ], min_cycle_length: 6 , max_cycle_length: 6, depth: 0 },
              tail: { label_type: [ induced_cycles, wl_labeled ], min_cycle_length: 6 , max_cycle_length: 6, depth: 0 },
              bias: { label_type: wl_labeled_edges, depth: 1 },
            },
            properties:
              { name: distances, values: [7,8,9,10,11,12 ] },
          },
          {
            bias: True,
            labels: {
              head: { label_type: [ induced_cycles, wl_labeled ], min_cycle_length: 6 , max_cycle_length: 6, depth: 0 },
              tail: { label_type: [ induced_cycles, wl_labeled ], min_cycle_length: 6 , max_cycle_length: 6, depth: 0 },
              bias: { label_type: wl_labeled_edges, depth: 1 },
            },
            properties:
              { name: distances, values: [13,14,15,16,17,18,19,20,21,22 ] },
          },
          {
            bias: True,
            labels: {
              head: { label_type: [ induced_cycles, wl_labeled ], min_cycle_length: 7 , max_cycle_length: 7, depth: 0 },
              tail: { label_type: [ induced_cycles, wl_labeled ], min_cycle_length: 7 , max_cycle_length: 7, depth: 0 },
              bias: { label_type: wl_labeled_edges, depth: 1 },
            },
            properties:
              { name: distances, values: [ 1,2,3,4,5,6 ] },
          },
          {
            bias: True,
            labels: {
              head: { label_type: [ induced_cycles, wl_labeled ], min_cycle_length: 7 , max_cycle_length: 7, depth: 0 },
              tail: { label_type: [ induced_cycles, wl_labeled ], min_cycle_length: 7 , max_cycle_length: 7, depth: 0 },
              bias: { label_type: wl_labeled_edges, depth: 1 },
            },
            properties:
              { name: distances, values: [ 7,8,9,10,11,12 ] },
          },
          {
            bias: True,
            labels: {
              head: { label_type: [ induced_cycles, wl_labeled ], min_cycle_length: 7 , max_cycle_length: 7, depth: 0 },
              tail: { label_type: [ induced_cycles, wl_labeled ], min_cycle_length: 7 , max_cycle_length: 7, depth: 0 },
              bias: { label_type: wl_labeled_edges, depth: 1 },
            },
            properties:
              { name: distances, values: [ 13,14,15,16,17,18,19,20,21,22 ] },
          },
          {
            bias: True,
            labels: {
              head: { label_type: [ induced_cycles, wl_labeled ], min_cycle_length: 8 , max_cycle_length: 8, depth: 0 },
              tail: { label_type: [ induced_cycles, wl_labeled ], min_cycle_length: 8 , max_cycle_length: 8, depth: 0 },
              bias: { label_type: wl_labeled_edges, depth: 1 },
            },
            properties:
              { name: distances, values: [ 1,2,3,4,5,6 ] },
          },
          {
            bias: True,
            labels: {
              head: { label_type: [ induced_cycles, wl_labeled ], min_cycle_length: 8 , max_cycle_length: 8, depth: 0 },
              tail: { label_type: [ induced_cycles, wl_labeled ], min_cycle_length: 8 , max_cycle_length: 8, depth: 0 },
              bias: { label_type: wl_labeled_edges, depth: 1 },
            },
            properties:
              { name: distances, values: [ 7,8,9,10,11,12 ] },
          },
          {
            bias: True,
            labels: {
              head: { label_type: [ induced_cycles, wl_labeled ], min_cycle_length: 8 , max_cycle_length: 8, depth: 0 },
              tail: { label_type: [ induced_cycles, wl_labeled ], min_cycle_length: 8 , max_cycle_length: 8, depth: 0 },
              bias: { label_type: wl_labeled_edges, depth: 1 },
            },
            properties:
              { name: distances, values: [ 13,14,15,16,17,18,19,20,21,22 ] },
          },
          {
            bias: True,
            labels: {
              head: { label_type: [ induced_cycles, wl_labeled ], min_cycle_length: 9 , max_cycle_length: 9, depth: 0 },
              tail: { label_type: [ induced_cycles, wl_labeled ], min_cycle_length: 9 , max_cycle_length: 9, depth: 0 },
              bias: { label_type: wl_labeled_edges, depth: 1 },
            },
            properties:
              { name: distances, values: [ 1,2,3,4,5,6 ] },
          },
          {
            bias: True,
            labels: {
              head: { label_type: [ induced_cycles, wl_labeled ], min_cycle_length: 9 , max_cycle_length: 9, depth: 0 },
              tail: { label_type: [ induced_cycles, wl_labeled ], min_cycle_length: 9 , max_cycle_length: 9, depth: 0 },
              bias: { label_type: wl_labeled_edges, depth: 1 },
            },
            properties:
              { name: distances, values: [ 7,8,9,10,11,12 ] },
          },
          {
            bias: True,
            labels: {
              head: { label_type: [ induced_cycles, wl_labeled ], min_cycle_length: 9 , max_cycle_length: 9, depth: 0 },
              tail: { label_type: [ induced_cycles, wl_labeled ], min_cycle_length: 9 , max_cycle_length: 9, depth: 0 },
              bias: { label_type: wl_labeled_edges, depth: 1 },
            },
            properties:
              { name: distances, values: [ 13,14,15,16,17,18,19,20,21,22 ] },
          },
        ],
    }
    - { layer_type: linear,
        mode: 'aggr_heads',
        output_features: 100,
        bias: True,
        activation: 'LeakyReLU',
    }
    - { layer_type: layer_norm }
    - { layer_type: aggregation,
        activation: 'None',
        bias: True,
        out_dim: 50,
        heads: [
          {
            bias: True,
            labels: { label_type: [ induced_cycles, wl_labeled_edges ], min_cycle_length: 6 , max_cycle_length: 6,
              depth: 0 },
          },
          {
            bias: True,
            labels: { label_type: [ induced_cycles, wl_labeled_edges ], min_cycle_length: 7 , max_cycle_length: 7,
              depth: 0 },
          },
          {
            bias: True,
            labels: { label_type: [ induced_cycles, wl_labeled_edges ], min_cycle_length: 8 , max_cycle_length: 8,
              depth: 0 },
          },
          {
              bias: True,
              labels: { label_type: [ induced_cycles, wl_labeled_edges ], min_cycle_length: 9 , max_cycle_length: 9,
              depth: 0 },
          },
          {
            bias: True,
            labels: { label_type: wl_labeled_edges, depth: 1 },
          },
          {
            bias: True,
            labels: { label_type: wl_labeled_edges, depth: 2 },
          }
        ],
    }
    - { layer_type: reshape }
    - { layer_type: linear,
        mode: 'aggr_features',
        output_features: 10,
        bias: True,
        activation: 'LeakyReLU',
    }
    - { layer_type: layer_norm }
    - { layer_type: linear,
        mode: 'aggr_features',
        output_features: 10,
        bias: True,
        activation: 'LeakyReLU',
    }
    - { layer_type: linear,
        mode: 'aggr_features',
        output_features: 1,
        bias: True,
        activation: 'None',
    }
    - { layer_type: reshape }